### ISSUE TITLE
open-source the code

### ISSUE THREAD

**Issue by huwenqing0606** [TheophileAbraham/intership#1]
Hi Theophile,

I wanted to see if we can open-source the code you implemented during the internship and we post it on our webpage here https://web.mst.edu/~huwen/ResearchTeam.html

We just make the repo public.

Let me know how you think,

thank you!

Wenqing

**Comment by TheophileAbraham** [comment]
Hi Mr Hu

Yes you can open source what I have done

Good continuation with your work

Théophile Abraham

**Comment by huwenqing0606** [comment]
Thanks Theophile. I think it may be easier you just set the current repo to be public? It is easy via settings. If it is not convenient for you to do that please just let me know and I will fork it to my account.

**Comment by huwenqing0606** [comment]
Hi Theophile, I tried to fork your repo, but since your repo is private the fork will be also private. So I think it may be best and easiest that you make your repo public. Let me know if there is difficulty in doing that. Thank you!

**Comment by TheophileAbraham** [comment]
Done
